# Generated by Django 4.2.4 on 2023-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
