# Generated by Django 4.2.5 on 2023-12-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0005_groupadmin_group_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
