# Generated by Django 4.2.5 on 2023-12-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0007_userprofilepic_firebase_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilepic",
            name="profile_picture",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
    ]
