# Generated by Django 4.2.5 on 2023-12-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0008_alter_userprofilepic_profile_picture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupAdmin",
        ),
    ]
