# Generated by Django 4.2.5 on 2023-12-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0009_delete_groupadmin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="admins",
        ),
        migrations.AddField(
            model_name="group",
            name="admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
