# Generated by Django 4.2.5 on 2023-12-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0011_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
